unbind C-b
setw -g mode-keys vi
set -g prefix C-a
set -g status-style 'bg=#262626 fg=#d7d7ff'
set -g mouse on
set -g renumber-windows on
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -selection c'
bind v split-window -h
bind s split-window -v
